### ISSUE TITLE
commons configuration module tests fail

### ISSUE THREAD

**Issue by simonetripodi** [manzke/guice-automatic-injection#11]
Launched the build, got the following errors:

[INFO] de.devsurf.injection.guice.integrations.commons.configurations  FAILURE [2.641s]

Tests in error: 
 createDynamicModule(de.devsurf.injection.guice.integrations.test.commons.configuration.url.URLConfigTests)
 createPListConfiguration(de.devsurf.injection.guice.integrations.test.commons.configuration.url.URLConfigTests)

noticed the stacktrace:

Unable to load the configuration from the URL http://devsurf.de/guice/configuration.plist

**Comment by manzke** [comment]
My domain was moving from one account to another. Should be fixed in 1 or 2 days.

**Comment by manzke** [comment]
should be back in action
