### ISSUE TITLE
race condition in ASMClasspathScanner

### ISSUE THREAD

**Issue by noblige** [manzke/guice-automatic-injection#12]
"visited" member is accessed from multiple threads (in scan() by submitting tasks to executor pool), yet collection is non-sychronized. Apparently this causes collection corruption and dead-locking.

Changing constructor to:

visited = Collections.synchronizedSet(new HashSet<String>());

evidently fixes that.

**Comment by manzke** [comment]
Hi,

thanks for the hint. I thought it doesn't matter, because it is not so hard, if one path is scanned twice. But if this really can have these effects, I'll change it.

Bye and Thanks,
Daniel
