### ISSUE TITLE
Create a stable release - not a snapshot

### ISSUE THREAD

**Issue by grouchal** [manzke/guice-automatic-injection#13]
We are not able to include snapshot releases in our projects as a matter of policy regarding stability and predictability of load.

Please can you create and deploy a stable version (non snapshot) version.

**Comment by grouchal** [comment]
OK I have seen this is a problem with your documentation - there are stable releases already deployed.

Please update your maven wiki pages to show version 0.8.7 not 0.8.2-SNAPSHOT

**Comment by manzke** [comment]
Thanks for the hint. I'll do it. :)
